import React from 'react';

const generateIdOrName = (label) => {
  return label ? label.toLowerCase().replace(/\s+/g, '-') : `input-${Math.random().toString(36).substr(2, 9)}`;
}

const Input = ({
  value,
  type = "text",
  id,
  name,
  onChange,
  disabled = false,
  autoComplete = "off",
  maxLength,
  minLength,
  required = false,
  placeholder = "",
  topSpace = 0,
  bottomSpace = 0,
  className = "",
  min,
  max,
  readOnly = false,
  accept,
  onKeyDown,
  successMessage,
  errorMessage,
  capture,
  label = "",
  list,
  autoCorrect,
  autoCapitalize,
  spellCheck,
  pattern,
  title
}) => {
  const autoGeneratedId = id || generateIdOrName(label || placeholder);
  const autoGeneratedName = name || generateIdOrName(label || placeholder);

  const validTopSpace = Math.min(Math.max(topSpace, 0), 5);
  const validBottomSpace = Math.min(Math.max(bottomSpace, 0), 5);

  return (
    <>
      <div className={`relative mt-${validTopSpace} mb-${validBottomSpace} ${className} text-left`}>
          {label && (
            <label htmlFor={autoGeneratedId} className="block mb-1 text-sm font-semibold text-black">{label}{required ? <span className="text-red-500"> *</span> : ""}</label>
          )}
          <input
            type={type}
            id={autoGeneratedId}
            name={autoGeneratedName}
            value={value}
            onChange={onChange}
            disabled={disabled}
            autoComplete={autoComplete}
            maxLength={maxLength}
            minLength={minLength}
            required={required}
            placeholder={placeholder}
            min={min}
            max={max}
            readOnly={readOnly}
            onKeyDown={onKeyDown}
            capture={capture}
            accept={accept}
            list={list}
            autoCorrect={autoCorrect}
            autoCapitalize={autoCapitalize}
            spellCheck={spellCheck}
            pattern={pattern}
            title={title}
            className="w-full rounded-lg bg-2 text-[18px] leading-[144.444%] px-6 py-5.5 text-black placeholder:text-[#6b6b6b] outline-none"
          />
          {successMessage && <p className="mt-2 text-sm text-green-600"><span className="font-medium">Success:</span> {successMessage}</p>}
          {errorMessage && <p className="mt-2 text-sm text-red-600"><span className="font-medium">Error:</span> {errorMessage}</p>}
        </div>
    </>
  );
}

export default Input;