import React from 'react';

const generateIdOrName = (label) => {
  return label ? label.toLowerCase().replace(/\s+/g, '-') : `input-${Math.random().toString(36).substr(2, 9)}`;
}

const Select = ({
  value,
  onChange,
  id,
  name,
  options = [],
  optionValue = 'value',
  optionLabel = 'label',
  placeholder = 'Select an option',
  label = "",
  topSpace = 0,
  bottomSpace = 0,
  required = false,
  className = '',
  disabled = false
}) => {

  const autoGeneratedId = id || generateIdOrName(label || placeholder);
  const autoGeneratedName = name || generateIdOrName(label || placeholder);

  const validTopSpace = Math.min(Math.max(topSpace, 0), 5);
  const validBottomSpace = Math.min(Math.max(bottomSpace, 0), 5);


  const getNestedValue = (obj, path) => {
    return path.split('.').reduce((value, key) => value?.[key], obj);
  };

  return (
    <div className={`relative text-left mb-${validBottomSpace} mt-${validTopSpace} ${className}`}>
      {label && (
        <label htmlFor={autoGeneratedId} className="block mb-1 text-sm font-medium text-black">{label}{required ? <span className="text-red-500"> *</span> : ""}</label>
      )}
      <select
        aria-label={label || placeholder}
        value={value}
        onChange={onChange}
        required={required}
        id={autoGeneratedId}
        name={autoGeneratedName}
        disabled={disabled}
        className="w-full rounded-lg bg-2 text-[18px] leading-[144.444%] px-6 py-5.5 text-black placeholder:text-[#6b6b6b] outline-none appearance-none"
      >
        <option value="" disabled selected>
          {placeholder}
        </option>
        {options?.map((option, i) => (
          <option key={i} value={getNestedValue(option, optionValue)}>
            {getNestedValue(option, optionLabel)}
          </option>
        ))}
      </select>
    </div>
  );
};

export default Select;
