import React from 'react'

const generateIdOrName = (label) => {
  return label ? label.toLowerCase().replace(/\s+/g, '-') : `input-${Math.random().toString(36).substr(2, 9)}`;
}

const Textarea = ({
  value,
  id,
  name,
  onChange,
  disabled = false,
  maxLength,
  required = false,
  placeholder = "",
  label = "",
  topSpace = 0,
  bottomSpace = 0,
  className = "",
  rows
}) => {

  const autoGeneratedId = id || generateIdOrName(label || placeholder);
  const autoGeneratedName = name || generateIdOrName(label || placeholder);

  const validTopSpace = Math.min(Math.max(topSpace, 0), 5);
  const validBottomSpace = Math.min(Math.max(bottomSpace, 0), 5);
  return (
    <div className={`relative text-left mt-${validTopSpace} mb-${validBottomSpace} ${className}`}>
      {label && (
        <label htmlFor={autoGeneratedId} className="block mb-2 text-sm font-medium text-black">
          {label}
        </label>
      )}
      <textarea
        rows={rows}
        value={value}
        onChange={onChange}
        disabled={disabled}
        maxLength={maxLength}
        required={required}
        placeholder={placeholder}
        id={autoGeneratedId}
        name={autoGeneratedName}
        className="w-full rounded-lg bg-2 text-[18px] leading-[144.444%] px-6 py-5.5 text-black placeholder:text-[#6b6b6b] outline-none"
      />
    </div>
  )
}

export default Textarea